version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/node/Dockerfile"
    container_name: "watchticator_api"
    restart: 'always'
    # links:
    #   - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./:/app